version: '3.8'

services:
  # WhatsApp API service
  whatsapp-api:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://whatsapp:password@postgres:5432/whatsapp_api
      - REDIS_URL=redis://redis:6379
      - META_APP_ID=${META_APP_ID}
      - META_APP_SECRET=${META_APP_SECRET}
      - WHATSAPP_TOKEN=${WHATSAPP_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - WEBHOOK_VERIFY_TOKEN=${WEBHOOK_VERIFY_TOKEN}
      - FREE_TIER_LIMIT=${FREE_TIER_LIMIT:-1000}
      - ALERT_THRESHOLD_PERCENT=${ALERT_THRESHOLD_PERCENT:-80}
      - CRITICAL_THRESHOLD_PERCENT=${CRITICAL_THRESHOLD_PERCENT:-95}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=whatsapp_api
      - POSTGRES_USER=whatsapp
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U whatsapp -d whatsapp_api"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Optional: Prisma Studio for database administration
  prisma-studio:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://whatsapp:password@postgres:5432/whatsapp_api
    command: sh -c "npm install prisma @prisma/client && npx prisma studio --hostname 0.0.0.0 --port 5555"
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    profiles:
      - studio

  # Optional: Redis Commander for Redis administration
  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    profiles:
      - admin

volumes:
  postgres_data:
  redis_data: