"""Update database schema with new models

Revision ID: 6d9c1f22dac9
Revises: fd67f438f07b
Create Date: 2025-08-21 17:33:57.064316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9c1f22dac9'
down_revision: Union[str, None] = 'fd67f438f07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('ico', sa.String(length=8), nullable=True),
    sa.Column('dic', sa.String(length=12), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('vat_payer', sa.Boolean(), nullable=True),
    sa.Column('vat_registration_date', sa.Date(), nullable=True),
    sa.Column('vat_period', sa.String(length=20), nullable=True),
    sa.Column('subscription_status', sa.Enum('INACTIVE', 'TRIAL', 'ACTIVE', 'EXPIRED', 'CANCELLED', name='subscriptionstatus'), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('subscription_until', sa.DateTime(), nullable=True),
    sa.Column('trial_transactions_used', sa.Integer(), nullable=True),
    sa.Column('trial_transactions_limit', sa.Integer(), nullable=True),
    sa.Column('activation_token', sa.String(length=64), nullable=True),
    sa.Column('activation_expires_at', sa.DateTime(), nullable=True),
    sa.Column('whatsapp_activated', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('current_year_revenue', sa.Float(), nullable=True),
    sa.Column('last_12_months_revenue', sa.Float(), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=True),
    sa.Column('tax_type', sa.String(length=20), nullable=True),
    sa.Column('default_vat_rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activation_token'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_table('conversation_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('partial_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_ico', sa.String(length=8), nullable=True),
    sa.Column('client_dic', sa.String(length=12), nullable=True),
    sa.Column('client_address', sa.Text(), nullable=True),
    sa.Column('amount_without_vat', sa.Float(), nullable=True),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('vat_rate', sa.Integer(), nullable=True),
    sa.Column('amount_without_vat', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('counterparty_ico', sa.String(length=8), nullable=True),
    sa.Column('counterparty_dic', sa.String(length=12), nullable=True),
    sa.Column('counterparty_address', sa.Text(), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('variable_symbol', sa.String(length=20), nullable=True),
    sa.Column('constant_symbol', sa.String(length=20), nullable=True),
    sa.Column('specific_symbol', sa.String(length=20), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vat_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('period_quarter', sa.Integer(), nullable=True),
    sa.Column('input_vat_base_21', sa.Float(), nullable=True),
    sa.Column('input_vat_21', sa.Float(), nullable=True),
    sa.Column('input_vat_base_12', sa.Float(), nullable=True),
    sa.Column('input_vat_12', sa.Float(), nullable=True),
    sa.Column('input_vat_base_10', sa.Float(), nullable=True),
    sa.Column('input_vat_10', sa.Float(), nullable=True),
    sa.Column('output_vat_base_21', sa.Float(), nullable=True),
    sa.Column('output_vat_21', sa.Float(), nullable=True),
    sa.Column('output_vat_base_12', sa.Float(), nullable=True),
    sa.Column('output_vat_12', sa.Float(), nullable=True),
    sa.Column('output_vat_base_10', sa.Float(), nullable=True),
    sa.Column('output_vat_10', sa.Float(), nullable=True),
    sa.Column('vat_liability', sa.Float(), nullable=True),
    sa.Column('vat_refund', sa.Float(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('ocr_processed', sa.Boolean(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_data', sa.JSON(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('vat_rate', sa.Integer(), nullable=True),
    sa.Column('total_without_vat', sa.Float(), nullable=True),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('total_with_vat', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_items')
    op.drop_table('attachments')
    op.drop_table('vat_records')
    op.drop_table('transactions')
    op.drop_table('payments')
    op.drop_table('invoices')
    op.drop_table('conversation_states')
    op.drop_table('users')
    # ### end Alembic commands ###
